gcc: Oe-selftest failure analysis - fix for tcl errors
gcc testsuite unable to read the value of variable $do-what-limit and causing below tcl errors.
ERROR: can't read "do": no such variable
    while executing
"set do_what $do-what-limit"

To fix this, quote the variable using braces, as in ${do-what-limit}.

Signed-off-by: Harish Sadineni <Harish.Sadineni@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>